name: GitHub Actions Workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  merge:
    branches:
      - '*'

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"event_type": "${{ github.event_name }}", "author": "${{ github.actor }}", "from_branch": "${{ github.head_ref }}", "to_branch": "${{ github.base_ref }}", "timestamp": "${{ github.event.created_at }}"}' \
          https://your-webhook-endpoint.com/webhook
