name: Webhook Trigger

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "event_type": "${{ github.event_name }}",
            "author": "${{ github.actor }}",
            "from_branch": "${{ github.event.before }}",
            "to_branch": "${{ github.event.ref }}",
            "timestamp": "$(date -u)"
          }' $WEBHOOK_URL
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
